fix unresolved method in case of MappingDriverChain configuration
Ecodev/graphql-doctrine pull request #2
Opened 2017-08-22 11:39 UTC by octaharon

in my symfony configuration current version fails when trying to explicitly call "getReader" of an object, which turns out to be a MappingDriverChain object instead of expected AnnotationDriver, I suppose

2017-08-22 14:14 UTC, PowerKiKi commented
I fixed a few code style, but it still miss unit tests to be merged. Would please add them to reach 100% coverage ?

2017-08-22 14:32 UTC, octaharon commented
I'm not sure I fully understand what's going on in your code, it's basically my first attempt on GraphQL in PHP ever, so for now I can't promise I'll attend to that. I'll continue using this library and if I manage to know it well enough I might contribute something more substantial and with more of an attitude. For now I just want to be sure it won't break my app when installed from repo, currently I need to maintain this particular change locally

2017-08-22 17:24 UTC, PowerKiKi commented
Fair enough, you can come back to this whenever you feel is appropriate for
you.

I myself have a tight deadline for my project, so I need to focus on our
needs for the time being and will leave this as is.

2017-08-22 17:46 UTC, octaharon commented
what's wrong about merging this one as it is? That could probably help another 380 people, who downloaded this. Even without unit tests it obviously reduces possible amount of errors one can encounter while using this at least by 1. We all have our deadlines though, and that's why I've fixed this tool so I could use it instead of another package - it totally helps me reach mine. Nice job.

2017-08-22 19:21 UTC, PowerKiKi commented
I believe it's better to always cover code with unit tests, without
exception. Otherwise it would set a precedent and we'll have to waste time
arguing why or why not such and such PR need tests.

On Aug 22, 2017 7:46 PM, "Alexander Uskov" <notifications@github.com> wrote:

> what's wrong about merging this one as it is? That could probably help
> another 380 people, who downloaded this. Even without unit tests it
> obviously reduces possible amount of errors one can encounter while using
> this at least by 1. We all have our deadlines though, and that's why I've
> fixed this tool so I could use it instead of another package - it totally
> helps me reach mine. Nice job.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ecodev/graphql-doctrine/pull/2#issuecomment-324101229>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAEbm3E88WNRofEZvjYGVxcSLBficPFlks5saxP8gaJpZM4O-fqz>
> .
>

2018-04-17 14:36 UTC, bkeetman approved these changes

2018-04-19 12:50 UTC, PowerKiKi commented
@bkeetman if the support for chained driver is important to you, please consider rebasing this PR and add tests to cover it.

2018-04-19 12:51 UTC, PowerKiKi requested changes
need tests

2018-06-21 07:06 UTC, PowerKiKi commented
Closing as this now seems outdated.

2018-06-21 07:06 UTC, closed without merging