Allow to retrieve AnnotationReader when entity manager uses MappingChain
Ecodev/graphql-doctrine pull request #4
Opened 2017-12-09 11:09 UTC by danydev

2017-12-09 12:35 UTC, PowerKiKi requested changes
This is an almost duplicate of #2, but it doesn't really matter for me.

We'll definitely have to cover it with tests though. As of now the lib has 100% coverage and we should keep it that way.

What would be your argument in favor of Mockery instead of out-of-the-box PHPUnit ? I am not familiar with the former, but it seems functionally equivalent, so why should we add a new dependency for that ?

2017-12-09 14:19 UTC, danydev commented
Oh, I didn't see someone else noticed the same limitation. Yes, the PRs are almost equivalent.

When I said introduce Mockery or equivalent I meant introducing mocks in tests (so if you don't feel comfortable with Mockery's mocks, PHPUnit's mocks are good enough), and that's because from a quick inspection I saw most of the tests are basically integration tests. So mine was just a general advice to make tests more unit-test oriented.

For example adding an integration test for this kind of change, it's a non-obvious thing to achieve, since I would need to deal with Doctrine's EM details configuration. While a unit test approach could make it a bit easier to target it.

I'm going to park the case, but as soon I get some spare time, I'll dig on it to add the test

2017-12-09 15:13 UTC, PowerKiKi commented
I agree with you, unit tests would be best. But in this specific case integration tests are not that terrible, because they are super fast and still allows for a very high coverage. But again, I have nothing against unit tests, on the contrary. But I feel integration tests can be faster to write in some cases.

Anyway, I'll wait for your tests to re-evaluate merging this PR. I might prefer going with pure PHPUnit, but if you can show me the benefit of Mockery, then I would be open to it too...

2018-05-25 15:44 UTC, TomHAnderson commented on src/Factory/AbstractFieldsConfigurationFactory.php
> +            foreach ($mappingDriver->getDrivers() as $driver) {
This only allows annotations on one driver.  Often when using a MappingDriverChain there will be multiple drivers which may each use annotations.

2018-09-27 04:49 UTC, PowerKiKi commented
Duplicated by #19 which looks more promising

2018-09-27 04:49 UTC, closed without merging